// <auto-generated></auto-generated>
using System;
using System.Collections;
using System.Collections.Generic;
namespace TestAutoGeneratedAndNullable
{
    //  C.1.cs(8, 26): [CS0265] C.1.cs(9,26): error CS0265: Partial declarations of 'C<T>' have inconsistent constraints for type parameter 'T'
    public partial class C<T> : IEnumerable<T>
    {
        public void M(string a)
        {
        }
    
        public IEnumerator<T> GetEnumerator(){ yield break; }
    
        IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
    }  
}
