// <auto-generated></auto-generated>
using System;
using System.Collections;
using System.Collections.Generic;

namespace TestAutoGeneratedAndNullable
{
    public partial class C<T> : IEnumerable<T>
    {
        public void M(string a)
        {
        }
    
        public IEnumerator<T> GetEnumerator(){ yield break; }
    
        IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
    }  
}
